version: '3.8'

services:
  whatsapp-automation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount a volume for persistent data if needed
      - whatsapp-data:/app/data

volumes:
  whatsapp-data:
